function RTW_rtwnameSIDMap() {
	this.rtwnameHashMap = new Array();
	this.sidHashMap = new Array();
	this.rtwnameHashMap["<Root>"] = {sid: "CurrentSencerError"};
	this.sidHashMap["CurrentSencerError"] = {rtwname: "<Root>"};
	this.rtwnameHashMap["<S1>"] = {sid: "CurrentSencerError:3"};
	this.sidHashMap["CurrentSencerError:3"] = {rtwname: "<S1>"};
	this.rtwnameHashMap["<S2>"] = {sid: "CurrentSencerError:4"};
	this.sidHashMap["CurrentSencerError:4"] = {rtwname: "<S2>"};
	this.rtwnameHashMap["<Root>/In1"] = {sid: "CurrentSencerError:1"};
	this.sidHashMap["CurrentSencerError:1"] = {rtwname: "<Root>/In1"};
	this.rtwnameHashMap["<Root>/Chart1"] = {sid: "CurrentSencerError:3"};
	this.sidHashMap["CurrentSencerError:3"] = {rtwname: "<Root>/Chart1"};
	this.rtwnameHashMap["<Root>/Model Info"] = {sid: "CurrentSencerError:4"};
	this.sidHashMap["CurrentSencerError:4"] = {rtwname: "<Root>/Model Info"};
	this.rtwnameHashMap["<Root>/Out1"] = {sid: "CurrentSencerError:5"};
	this.sidHashMap["CurrentSencerError:5"] = {rtwname: "<Root>/Out1"};
	this.rtwnameHashMap["<S1>:91"] = {sid: "CurrentSencerError:3:91"};
	this.sidHashMap["CurrentSencerError:3:91"] = {rtwname: "<S1>:91"};
	this.rtwnameHashMap["<S1>:31"] = {sid: "CurrentSencerError:3:31"};
	this.sidHashMap["CurrentSencerError:3:31"] = {rtwname: "<S1>:31"};
	this.rtwnameHashMap["<S1>:92"] = {sid: "CurrentSencerError:3:92"};
	this.sidHashMap["CurrentSencerError:3:92"] = {rtwname: "<S1>:92"};
	this.rtwnameHashMap["<S1>:74"] = {sid: "CurrentSencerError:3:74"};
	this.sidHashMap["CurrentSencerError:3:74"] = {rtwname: "<S1>:74"};
	this.rtwnameHashMap["<S1>:33"] = {sid: "CurrentSencerError:3:33"};
	this.sidHashMap["CurrentSencerError:3:33"] = {rtwname: "<S1>:33"};
	this.rtwnameHashMap["<S1>:93"] = {sid: "CurrentSencerError:3:93"};
	this.sidHashMap["CurrentSencerError:3:93"] = {rtwname: "<S1>:93"};
	this.rtwnameHashMap["<S1>:89"] = {sid: "CurrentSencerError:3:89"};
	this.sidHashMap["CurrentSencerError:3:89"] = {rtwname: "<S1>:89"};
	this.rtwnameHashMap["<S1>:75"] = {sid: "CurrentSencerError:3:75"};
	this.sidHashMap["CurrentSencerError:3:75"] = {rtwname: "<S1>:75"};
	this.rtwnameHashMap["<S1>:94"] = {sid: "CurrentSencerError:3:94"};
	this.sidHashMap["CurrentSencerError:3:94"] = {rtwname: "<S1>:94"};
	this.rtwnameHashMap["<S2>/EmptySubsystem"] = {sid: "CurrentSencerError:4:1"};
	this.sidHashMap["CurrentSencerError:4:1"] = {rtwname: "<S2>/EmptySubsystem"};
	this.getSID = function(rtwname) { return this.rtwnameHashMap[rtwname];}
	this.getRtwname = function(sid) { return this.sidHashMap[sid];}
}
RTW_rtwnameSIDMap.instance = new RTW_rtwnameSIDMap();
